try:
    from typing import Protocol, runtime_checkable, Optional, Tuple
except ImportError:
    Protocol = object
    runtime_checkable = lambda cls: cls
    Optional = None
    Tuple = None


@runtime_checkable
class PinInterface(Protocol):
    def value(self, v: Optional[int] = None) -> Optional[int]: ...
    def on(self) -> None: ...
    def off(self) -> None: ...


@runtime_checkable
class ADCInterface(Protocol):
    def read(self) -> int: ...


@runtime_checkable
class NetworkInterface(Protocol):
    def active(self, v: Optional[bool] = None) -> Optional[bool]: ...
    def connect(self, ssid: str, password: str) -> None: ...
    def isconnected(self) -> bool: ...
    def ifconfig(self) -> Tuple: ...
    def scan(self) -> list: ...
    def disconnect(self) -> None: ...
    def status(self) -> int: ...
    def config(self, *args, **kwargs): ...


@runtime_checkable
class TimeInterface(Protocol):
    def localtime(self) -> Tuple: ...


@runtime_checkable
class SystemInterface(Protocol):
    def get_cpu_freq(self) -> int: ...
    def set_cpu_freq(self, freq: int) -> None: ...
    def deep_sleep(self, duration_ms: int) -> None: ...
    def reset(self) -> None: ...


@runtime_checkable
class PinFactory(Protocol):
    def make_input_pin(self, pin_no: int) -> PinInterface: ...
    def make_output_pin(self, pin_no: int) -> PinInterface: ...
    def make_adc(self, pin_no: int) -> ADCInterface: ...
