M48
; DRILL file {KiCad (7.0.0)} date Tue May 30 23:08:42 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-30T23:08:42+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X25.515Y-18.4
X30.365Y-18.4
T2
X25.215Y-15.37
X30.665Y-15.37
T0
M30
